# =============================================================================
# global.R — 2025 Attendance Bright Spots Shiny App
#
# Loaded once at startup (shared across all sessions).
# Contains: libraries, constants, data loading, grade band helpers,
#           NC boundaries, map palette, and the popup builder used by
#           both the initial render and the leaflet proxy updates in server.R.
# =============================================================================

# Libraries ####

library(shiny)
library(tidyverse)
library(leaflet)
library(reactable)
library(htmltools)
library(bslib)


# Constants ####

CANDIDATE_YEAR <- 2025 # Year being evaluated
NCDPI_NAVY <- "#003A70"

GRADE_BAND_LEVELS <- c(
  "Elementary (K-5)",
  "Elem-Mid (K-8)",
  "Middle (6-8)",
  "Mid-High (6-12)",
  "High (9-12)",
  "K-12/Combined",
  "Other/Unparsed"
)

NCDPI_BRAND_COLORS <- c(
  "Elementary (K-5)" = "#003A70",
  "Middle (6-8)" = "#922880",
  "High (9-12)" = "#29B5D9",
  "Elem-Mid (K-8)" = "#FF9015",
  "Mid-High (6-12)" = "#74C04B",
  "K-12/Combined" = "#B7B9BB",
  "Other/Unparsed" = "#d0d0d0"
)

DECREASE_THRESHOLDS <- list(
  list(label = "\u226550% decrease", min = 0.50, max = Inf),
  list(label = "40\u201349% decrease", min = 0.40, max = 0.50),
  list(label = "30\u201339% decrease", min = 0.30, max = 0.40),
  list(label = "20\u201329% decrease", min = 0.20, max = 0.30),
  list(label = "10\u201319% decrease", min = 0.10, max = 0.20)
)

THRESHOLD_LABELS <- map_chr(DECREASE_THRESHOLDS, "label")


# =============================================================================
# Grade Band Classification Helpers ####
# =============================================================================

normalize_span <- function(span) {
  span |>
    as.character() |>
    toupper() |>
    trimws() |>
    str_replace_all("\\s+", "") |>
    str_replace_all(":", "-")
}

parse_grade_token <- function(x) {
  x <- toupper(trimws(x))
  if (x %in% c("K", "KG", "0K")) {
    return(0L)
  }
  if (x %in% c("PK", "PREK")) {
    return(-1L)
  }
  if (str_detect(x, "^[0-9]{1,2}$")) {
    return(as.integer(x))
  }
  NA_integer_
}

grade_band_from_span <- function(span) {
  if (is.na(span) || trimws(span) == "") {
    return(NA_character_)
  }
  s <- normalize_span(span)
  parts <- str_split(s, "-", n = 2, simplify = TRUE)
  if (ncol(parts) != 2) {
    return("Other/Unparsed")
  }
  g1 <- parse_grade_token(parts[1])
  g2 <- parse_grade_token(parts[2])
  if (is.na(g1) || is.na(g2)) {
    return("Other/Unparsed")
  }
  if (g2 <= 5) {
    return("Elementary (K-5)")
  }
  if (g1 >= 6 && g2 <= 8) {
    return("Middle (6-8)")
  }
  if (g1 >= 9 && g2 <= 12) {
    return("High (9-12)")
  }
  if (g1 <= 5 && g2 <= 8) {
    return("Elem-Mid (K-8)")
  }
  if (g1 >= 6 && g2 >= 9) {
    return("Mid-High (6-12)")
  }
  if (g1 <= 5 && g2 >= 9) {
    return("K-12/Combined")
  }
  "Other/Unparsed"
}

grade_band_from_span_vec <- Vectorize(grade_band_from_span, USE.NAMES = FALSE)


# =============================================================================
# Load Pre-Built Candidate Pool ####
#
# bright_spot_candidates.rds is generated by 2025-map.R and bundled with
# the app so shinyapps.io does not need access to local source files.
# =============================================================================

bright_spot_candidates <- readRDS("data/bright_spot_candidates.rds")


# =============================================================================
# Filter Choice Vectors (used by ui.R) ####
# =============================================================================

app_county_choices <- sort(unique(na.omit(bright_spot_candidates$county)))
grade_band_choices <- GRADE_BAND_LEVELS[
  GRADE_BAND_LEVELS %in% unique(bright_spot_candidates$grade_band)
]
poverty_choices <- sort(unique(na.omit(bright_spot_candidates$poverty)))
enroll_range <- range(bright_spot_candidates$den, na.rm = TRUE)


# =============================================================================
# Map Palette ####
# =============================================================================

grade_band_palette <- colorFactor(
  palette = NCDPI_BRAND_COLORS,
  levels = GRADE_BAND_LEVELS,
  domain = bright_spot_candidates$grade_band
)


# =============================================================================
# NC Boundary Polygons ####
# =============================================================================

nc_state_boundary <- readRDS("data/nc_state_boundary.rds")
nc_county_boundaries <- readRDS("data/nc_county_boundaries.rds")


# =============================================================================
# Popup Builder ####
# =============================================================================

make_school_popups <- function(df) {
  unname(mapply(
    function(
      name,
      county,
      grade_band,
      poverty,
      den,
      year_peak,
      p_peak,
      p_current,
      improvement_pp,
      pct_decrease
    ) {
      paste0(
        "<div style='font-family: Arial, sans-serif; min-width: 250px;'>",
        "<h4 style='margin: 0 0 10px 0; color: ",
        NCDPI_NAVY,
        ";'>",
        name,
        "</h4>",
        "<p style='margin: 5px 0;'>",
        "<strong>County:</strong> ",
        if_else(is.na(county), "Unknown", county),
        "<br>",
        "<strong>Grade Band:</strong> ",
        if_else(is.na(grade_band), "Unknown", grade_band),
        "<br>",
        "<strong>Poverty:</strong> ",
        if_else(is.na(poverty), "Unknown", poverty),
        "<br>",
        "<strong>Enrollment:</strong> ",
        as.integer(den),
        "</p>",
        "<hr style='margin: 10px 0; border-top: 1px solid #ccc;'>",
        "<p style='margin: 5px 0;'><strong>Chronic Absenteeism Rates:</strong><br>",
        "Peak (",
        as.integer(year_peak),
        "): ",
        "<span style='color: #e74c3c; font-weight: bold;'>",
        round(p_peak * 100, 1),
        "%</span><br>",
        "Current (",
        CANDIDATE_YEAR,
        "): ",
        "<span style='color: #27ae60; font-weight: bold;'>",
        round(p_current * 100, 1),
        "%</span>",
        "</p>",
        "<hr style='margin: 10px 0; border-top: 1px solid #ccc;'>",
        "<p style='margin: 5px 0;'><strong>Performance:</strong><br>",
        "Improvement: <strong>",
        round(improvement_pp, 1),
        " pp</strong><br>",
        "Percent Decrease: <strong>",
        round(pct_decrease * 100, 1),
        "%</strong>",
        "</p></div>"
      )
    },
    df$name,
    df$county,
    df$grade_band,
    df$poverty,
    df$den,
    df$year_peak,
    df$p_peak,
    df$p_current,
    df$improvement_pp,
    df$pct_decrease,
    SIMPLIFY = TRUE
  ))
}


# =============================================================================
# Reactable Theme (shared) ####
# =============================================================================

ncdpi_table_theme <- reactableTheme(
  borderColor = "#dee2e6",
  stripedColor = "#f5f8fc",
  highlightColor = "#eaf1fb",
  headerStyle = list(
    background = "#ffffff",
    color = NCDPI_NAVY,
    fontWeight = "700",
    fontSize = "14px",
    borderBottom = paste0("3px solid ", NCDPI_NAVY),
    textTransform = "uppercase",
    letterSpacing = "0.05em"
  )
)
